---
#- name: Install netdata
#  apt:
#    pkg:
#    - netdata

- name: install prerequisites
  apt: update_cache=yes name={{ item }} state=present
  with_items:
    - sendmail
    - zlib1g-dev
    - uuid-dev
    - libuv1-dev
    - liblz4-dev
    - libjudy-dev
    - libssl-dev
    - libmnl-dev
    - gcc
    - make
    - git
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - pkg-config
    - curl
    - lm-sensors
    - python
    - cmake
    - python-yaml
    - python-psycopg2
    - libmnl0
    - netcat
    - curl
    - rsyslog
    - apt-transport-https
    - python2.7
    - python-pip
    - python-jinja2
    - git
    - nano
    - procps
    - wget
    - cmake
    - make
    - build-essential
    - libpcre3
    - libpcre3-dev
    - libssl-dev
    - zlibc
    - zlib1g
    - zlib1g-dev
    - libgeoip-dev
    - pkg-config
    - libjansson-dev
    - bison
    - libexpat1-dev
    - expect
    - libgd-dev
    - gettext
    - libjansson-dev
    - libjpeg-dev
    - libc6-dev
    - libc-dev-bin
    - libopenjp2-7-dev
    - libldap2-dev
    - libghc-regex-pcre-dev
    - libperl-dev
    - libreadline-dev
    - libsqlite0-dev
    - libghc-zlib-dev
    - libctpp2-2v5
    - ctpp2-utils
    - libctpp2-dev
    - libgd-dev
    - gettext
    - gettext-base
    - libint-dev
    - apache2-utils
    - pax-utils


- name: download netdata software
  get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: /usr/local/src/

- name: install netdata
  shell: bash /usr/local/src/kickstart.sh --dont-wait

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: netdata
    group: netdata
  become: true
  with_items:
    - /var/cache/netdata
    - /var/log/netdata

- name: Ensure configuration directory exists
  file:
    name: "{{ netdata_conf_dir }}"
    state: directory

- name: Copy netdata configuration
  template:
    src: netdata.conf.j2
    dest: "{{ netdata_conf }}"

- name: Configure alarms discord
  template:
    src: health_alarm_notify.conf.j2
    dest: /etc/netdata/health_alarm_notify.conf

- name: Configure alarms cpu
  copy:
    src: cpu.conf
    dest: /etc/netdata/health.d/cpu.conf

- name: Configure alarms load
  copy:
    src: load.conf
    dest: /etc/netdata/health.d/load.conf 

- name: Configure alarms disks
  copy:
    src: disks.conf
    dest: /etc/netdata/health.d/disks.conf

- name: Configure alarms ram
  copy:
    src: ram.conf
    dest: /etc/netdata/health.d/ram.conf

- name: Configure dbengine
  copy:
    src: dbengine.conf
    dest: /etc/netdata/health.d/dbengine.conf

- name: Creates directory dbengine
  file:
    path: /var/cache/netdata/dbengine
    state: directory

- name: Configuration sendmail
  shell: echo "Y" | sendmailconfig

- name: Configure sendmail
  template:
    src: sendmail.mc.j2
    dest: /etc/mail/sendmail.mc

- name: Configure submit
  copy:
    src: submit.mc
    dest: /etc/mail/submit.mc

- name: Create a directory authinfo if it does not exist
  file:
    path: /etc/mail/authinfo
    state: directory

- name: Configure auth for sendmail
  template:
    src: smtp-auth.j2
    dest: /etc/mail/authinfo/smtp-auth

- name: Command makemap in the auth
  shell: makemap hash /etc/mail/authinfo/smtp-auth < /etc/mail/authinfo/smtp-auth

- name: Command m4 for sendmail
  shell: m4 /etc/mail/sendmail.mc > /etc/mail/sendmail.cf && m4 /etc/mail/submit.mc > /etc/mail/submit.cf && make -C /etc/mail

- name: Restart sendmail
  service:
   name: sendmail
   state: restarted
   enabled: true

- name: Restart netdata
  service:
    name: netdata
    state: restarted
    enabled: true
